gantt
todayMarker off
dateFormat  HH
axisFormat %H

section 选第2个活动
a1: active, 01, 04
a2: done, 03, 05
a3: done, 00, 06
a4: done, 05, 07

section 选第3个活动
a1: active, 01, 04
a4: active, 05, 07
a5: done, 03, 09
a6: done, 05, 09
a7: done, 06, 10
a8: done, 08, 11

section 选第4个活动
a1: active, 01, 04
a4: active, 05, 07
a8: active, 08, 11
a9: done, 08, 12
a10: done, 02, 14
a11: done, 12, 16

section 兼容活动
a1: active, 01, 04
a4: active, 05, 07
a8: active, 08, 11
a11: active, 12, 16